# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('N', 'Has not said'), ('S', 'Supports'), ('D', 'Denounces')], default='N', max_length=1)),
                ('shown_to_all', models.BooleanField(default=False)),
                ('extra_phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.Phone')),
            ],
        ),
    ]
