# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='chamber',
            field=models.CharField(choices=[('H', 'House of Representatives'), ('S', 'Senate')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politician',
            name='district',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='politician',
            name='state',
            field=models.CharField(default='PA', max_length=2),
            preserve_default=False,
        ),
    ]
