# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20161116_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='district',
        ),
        migrations.AddField(
            model_name='politician',
            name='district_or_class',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
