# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_auto_20161116_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='party',
            field=models.CharField(default='FAIL', max_length=50),
            preserve_default=False,
        ),
    ]
