# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_politician_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='district_or_class',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='party',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='state',
        ),
        migrations.AddField(
            model_name='politician',
            name='zipcode',
            field=models.CharField(default='00000', max_length=5),
            preserve_default=False,
        ),
    ]
