# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_auto_20161116_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='district_or_class',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
