# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0010_politician_district_or_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
