# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0011_politician_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician',
            old_name='zipcode',
            new_name='zip_or_state',
        ),
    ]
