# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0012_auto_20161116_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='extra_phones',
        ),
        migrations.AddField(
            model_name='phone',
            name='politician',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='call.Politician'),
            preserve_default=False,
        ),
    ]
