# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0013_auto_20161116_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='title',
            field=models.CharField(default='Speaker of the House', max_length=256),
            preserve_default=False,
        ),
    ]
