# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0016_auto_20161119_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='script',
            field=models.TextField(blank=True, default=None),
        ),
    ]
