# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0017_auto_20161119_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
