# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0020_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='shown_to_all',
        ),
        migrations.AddField(
            model_name='politician',
            name='shown_to_all',
            field=models.ManyToManyField(to='call.Campaign'),
        ),
    ]
