# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0021_auto_20161209_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='shown_to_all',
            field=models.ManyToManyField(blank=True, to='call.Campaign'),
        ),
    ]
