# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0022_auto_20161209_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hashtag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
