# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0024_auto_20170117_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='action',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
