# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0025_campaign_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='checker',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
