# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0026_campaign_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='include_representatives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='include_senators',
            field=models.BooleanField(default=True),
        ),
    ]
